version: '3.8'

services:
  my-postgres:
    image: postgres:latest
    container_name: postgres-on_your_markets
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./volume_postgres:/var/lib/postgresql/data